# Generated by Django 6.0.6 on 2026-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('clase_deadline', 'Plazo de Clase'), ('evaluacion_deadline', 'Plazo de Evaluación'), ('curso_start', 'Inicio de Curso'), ('curso_end', 'Fin de Curso'), ('evento_general', 'Evento General')], default='evento_general', max_length=25)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(default='#6366f1', help_text='Color hex, ej: #6366f1', max_length=7)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
