# Generated by Django 6.0.6 on 2026-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Hito')),
                ('descripcion', models.TextField(verbose_name='Descripción del Hito')),
            ],
            options={
                'verbose_name': 'Hito Clínico',
                'verbose_name_plural': 'Hitos Clínicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('nivel_dependencia', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa'), ('postrado', 'Postrado')], max_length=20, verbose_name='Nivel de Dependencia')),
                ('patologias', models.TextField(blank=True, verbose_name='Patologías Diagnósticas')),
                ('requerimientos_especiales', models.TextField(blank=True, verbose_name='Requerimientos Especiales')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
