# Generated by Django 6.0.6 on 2026-08-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hitoclinico',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores Asignados'),
        ),
        migrations.AddField(
            model_name='hitoclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_clinicos', to='pacientes.paciente'),
        ),
    ]
