# Generated by Django 6.0.6 on 2026-08-08 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hitoclinico',
            name='importancia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10, verbose_name='Nivel de Importancia'),
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Tarea o Medicamento')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles / Dosis')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Receta Activa')),
                ('colaborador_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador Titular')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Receta / Tarea Diaria',
                'verbose_name_plural': 'Recetas / Tareas Diarias',
            },
        ),
        migrations.CreateModel(
            name='RegistroRutinaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Completada')),
                ('completada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pacientes.recetamedica')),
            ],
            options={
                'verbose_name': 'Registro de Rutina',
                'verbose_name_plural': 'Registros de Rutinas',
            },
        ),
    ]
