# Generated by Django 6.0.6 on 2026-08-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_hitoclinico_importancia_recetamedica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAsignacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ia', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
