# Generated by Django 6.0.6 on 2026-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_reporteasignacionia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Paciente Activo'),
        ),
    ]
