# Generated by Django 6.0.6 on 2026-08-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
    ]
