# Generated by Django 6.0.6 on 2026-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_publico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banco de Preguntas',
                'verbose_name_plural': 'Bancos de Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('porcentaje_aprobacion', models.IntegerField(default=70)),
                ('max_intentos', models.IntegerField(default=0, help_text='0 = sin límite')),
                ('duracion_minutos', models.IntegerField(blank=True, help_text='Minutos, vacío = sin límite', null=True)),
                ('preguntas_por_intento', models.IntegerField(blank=True, help_text='Aleatorizar N preguntas del banco', null=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField()),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('respuestas', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
