# Generated by Django 6.0.6 on 2026-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en el curso'),
        ),
    ]
