# Generated by Django 6.0.6 on 2026-08-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_modulo_clase_modulo_modulo_modulo_orden_minimo'),
        ('evaluaciones', '0003_evaluacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='cursos.modulo'),
        ),
    ]
