# Generated by Django 6.0.6 on 2026-08-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, upload_to='entregas/%Y/%m/')),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('calificado', 'Calificado'), ('devuelto', 'Devuelto')], default='enviado', max_length=15)),
                ('puntaje_obtenido', models.IntegerField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True, default='')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha límite')),
                ('puntaje_maximo', models.IntegerField(default=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
