# Generated by Django 6.0.6 on 2026-08-08 20:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Color en formato hex, ej: #6366f1', max_length=7)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido de la clase')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de la clase en el curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='asignado', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video URL')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='ClaseCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='cursos.clase')),
            ],
            options={
                'verbose_name': 'Clase Completada',
                'verbose_name_plural': 'Clases Completadas',
            },
        ),
    ]
