# Generated by Django 6.0.6 on 2026-08-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecompletado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_completadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos.categoria'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='clasecompletado',
            unique_together={('usuario', 'clase')},
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='clase_curso_orden_uniq'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.CheckConstraint(condition=models.Q(('orden__gte', 1)), name='clase_orden_minimo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncurso',
            unique_together={('usuario', 'curso')},
        ),
    ]
