# Generated by Django 6.0.6 on 2026-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=0, help_text='Duración estimada en horas'),
        ),
    ]
