# Generated by Django 6.0.6 on 2026-08-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_duracion_horas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clase',
            name='clase_curso_orden_uniq',
        ),
    ]
