# Generated by Django 4.2 on 2026-08-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_clase_clase_curso_orden_uniq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='duracion_horas',
            new_name='duracion_minutos',
        ),
    ]
