# Generated by Django 6.0.6 on 2026-08-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_duracion_horas_curso_duracion_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='curso',
            name='exige_tiempo_minimo',
            field=models.BooleanField(default=False, help_text='Si es True, el alumno no puede completar el curso antes de un tiempo prudente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_exigidas',
            field=models.PositiveIntegerField(default=0, help_text='Horas totales exigidas para completar el curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_por_semana',
            field=models.PositiveIntegerField(default=0, help_text='Horas de dedicación semanal esperada'),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='inicio_atrasado',
            field=models.BooleanField(default=False, help_text='Indica si el alumno inició el curso con retraso y se le otorgó prórroga'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Duración estimada en minutos'),
        ),
    ]
