# Generated by Django 6.0.6 on 2026-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_curso_fecha_limite_curso_exige_tiempo_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='exige_tiempo_minimo',
            field=models.BooleanField(default=False, help_text='Evita que el alumno complete el curso en menos tiempo del exigido'),
        ),
    ]
