# Generated by Django 6.0.6 on 2026-08-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_curso_exige_tiempo_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del módulo en el curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='cursos.modulo'),
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.CheckConstraint(condition=models.Q(('orden__gte', 1)), name='modulo_orden_minimo'),
        ),
    ]
