# Generated by Django 6.0.6 on 2026-08-14 21:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_modulo_clase_modulo_modulo_modulo_orden_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='formato_evaluacion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Cómo se evaluarán los conocimientos adquiridos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fundamentacion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Justificación del curso según necesidades detectadas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='metodologia',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Metodología de enseñanza (ej: E-learning, Mixto)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivo_general',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Objetivo general de aprendizaje'),
        ),
        migrations.AddField(
            model_name='curso',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nombre o cargo del responsable de impartir el curso', max_length=200),
        ),
    ]
