# Generated by Django 6.0.6 on 2026-08-08 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
