# Generated by Django 6.0.6 on 2026-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_pacientes_personalizado',
            field=models.IntegerField(blank=True, help_text='Si se define, sobreescribe el límite del cargo del usuario.', null=True),
        ),
    ]
