# Generated by Django 6.0.6 on 2026-08-08 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSesionArt33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_visitado', models.CharField(max_length=200, verbose_name='Módulo Visitado')),
                ('fecha_entrada', models.DateTimeField(verbose_name='Fecha/Hora de Entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Salida')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_sesion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Sesión (Art. 33)',
                'verbose_name_plural': 'Registros de Sesión (Art. 33)',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
