# Generated by Django 6.0.6 on 2026-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNuevosCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteUpskilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
